server:
  port: 8082

spring:
  application:
    name: complaint-service
  data:
    mongodb:
      host: ***************
      port: 27017
      database: urban_complaints
      username: ***************
      password: ***************
      authentication-database: admin

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:***************}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

services:
  ai-insight-service:
    url: ***************

logging:
  level:
    com.urban.complaint: INFO

management:
  metrics:
    tags:
      application: complaint-service
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    kafka:
      enabled: true
    show-details: always

security:
  enabled: ${SECURITY_ENABLED:true}
  api-key: ${SECURITY_API_KEY:***************}
  admin-api-key: ${SECURITY_ADMIN_API_KEY:***************}
